#!/usr/bin/env perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use Data::Dmp;
use Getopt::Long::Util qw(parse_getopt_long_opt_spec);

for (@ARGV) {
    say "$_: ", dmp(parse_getopt_long_opt_spec($_));
}

# ABSTRACT: Parse Getopt::Long option specification
# PODNAME:

=head1 SYNOPSIS

 % parse-getopt-long-spec --foo=s '--bar!' '--baz=i@'
 --foo=s: {dash_prefix=>"--",desttype=>"",opts=>["foo"],type=>"s"}
 --bar!: {dash_prefix=>"--",is_neg=>1,opts=>["bar"]}
 --baz=i@: {dash_prefix=>"--",desttype=>"\@",opts=>["baz"],type=>"i"}
 /x: undef


=head1 DESCRIPTION

This is a helper script. You feed it one or more option specifications and the
script will parse them using L<Getopt::Long::Util>'s
C<parse_getopt_long_opt_spec> and show you the results.


=head1 SEE ALSO

L<Getopt::Long>

L<Getopt::Long::Util>
